In [10]:
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures

# Load the dataset
data = pd.read_csv('diabetes.csv')
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148,72,35,0.0,33.6,0.627,50.0,1
1,1.0,85,66,29,0.0,26.6,0.351,31.0,0
2,8.0,183,64,0,0.0,23.3,0.672,32.0,1
3,1.0,89,66,23,94.0,28.1,0.167,21.0,0
4,0.0,137,40,35,168.0,43.1,2.288,33.0,1
...,...,...,...,...,...,...,...,...,...
764,10.0,101,76,48,180.0,32.9,0.171,63.0,0
765,2.0,122,70,27,0.0,36.8,0.340,27.0,0
766,5.0,121,72,23,112.0,26.2,0.245,30.0,0
767,1.0,126,60,0,0.0,30.1,0.349,47.0,1
768,1.0,93,70,31,0.0,30.4,0.315,23.0,0

In [11]:
# Select the features for interaction
selected_features = data[['Age', 'BMI']]
selected_features

      Age   BMI
0    50.0  33.6
1    31.0  26.6
2    32.0  23.3
3    21.0  28.1
4    33.0  43.1
..    ...   ...
764  63.0  32.9
765  27.0  36.8
766  30.0  26.2
767  47.0  30.1
768  23.0  30.4

[769 rows x 2 columns]

In [15]:
data['New'] = data['Glucose'] + data['BloodPressure']
print("DataFrame with new column:")
print(data)

DataFrame with new column:
     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6.0      148             72             35      0.0  33.6
1            1.0       85             66             29      0.0  26.6
2            8.0      183             64              0      0.0  23.3
3            1.0       89             66             23     94.0  28.1
4            0.0      137             40             35    168.0  43.1
..           ...      ...            ...            ...      ...   ...
764         10.0      101             76             48    180.0  32.9
765          2.0      122             70             27      0.0  36.8
766          5.0      121             72             23    112.0  26.2
767          1.0      126             60              0      0.0  30.1
768          1.0       93             70             31      0.0  30.4

     DiabetesPedigreeFunction   Age  Outcome  New
0                       0.627  50.0        1  220
1                       0.351  31.0        0  151
2                       0.672  32.0        1  247
3                       0.167  21.0        0  155
4                       2.288  33.0        1  177
..                        ...   ...      ...  ...
764                     0.171  63.0        0  177
765                     0.340  27.0        0  192
766                     0.245  30.0        0  193
767                     0.349  47.0        1  186
768                     0.315  23.0        0  163

[769 rows x 10 columns]

In [7]:
print(data.loc[2])

Pregnancies                   8.000
Glucose                     183.000
BloodPressure                64.000
SkinThickness                 0.000
Insulin                       0.000
BMI                          23.300
DiabetesPedigreeFunction      0.672
Age                          32.000
Outcome                       1.000
Name: 2, dtype: float64

In [8]:
print(data["BloodPressure"].loc[2])

64

#### feature engineering is the process of using domain knowledge to extract features from raw data
#### These features can be used to imrove the performance of machine learning algorithms

### feature engineering
1 feature transformation
     1.Missing values imputation
     2.Outlier detection
     3.Feature scaling
2.Feature Construction
3.Feature Selection
4.Feature extraction